### ISSUE TITLE
KafkaMessageSenderPool

### ISSUE THREAD

**Issue by guodage** [DarkPhoenixs/message-queue-client-framework#1]
麻烦问下 KafkaMessageSenderPool#setZkhosts在什么情况下会用到呢？

**Comment by VictorZeng** [comment]
**生产者需要根据zookeeper的host连接kafka时可以用它。**
ZookeeperHosts这个对象是设置zookeeper host的相关信息，setZkhosts其实就是在zookeeper中扫描出kafka的host，kafka producer最终还是根据kafka host连接kafka server。

**Comment by guodage** [comment]
明白了 感谢 :)
